### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Wolfkid200444** [FutureDeveloperZ/RulesUI#1]
22:40:20[Server thread/CRITICAL]:  Unhandled exception executing command 'rules' in rules: Call to undefined method jojoe77777\FormAPI\SimpleForm::addLabel()

22:40:20[Server thread/CRITICAL]:  Error: "Call to undefined method jojoe77777\FormAPI\SimpleForm::addLabel()" (EXCEPTION) in "RulesUI_dev-10.phar/src/WolfGangRule/Rules" at line 56

22:40:20[Server thread/DEBUG]:  #0 RulesUI_dev-10.phar/src/WolfGangRule/Rules(43): WolfGangRule\Rules->mainForm(pocketmine\Player object)

22:40:20[Server thread/DEBUG]:  #1 src/pocketmine/command/PluginCommand(58): WolfGangRule\Rules->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string rules, array Array())

22:40:20[Server thread/DEBUG]:  #2 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string rules, array Array())

22:40:20[Server thread/DEBUG]:  #3 src/pocketmine/Server(1955): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string rules)

22:40:20[Server thread/DEBUG]:  #4 src/pocketmine/Player(2191): pocketmine\Server->dispatchCommand(pocketmine\Player object, string rules)

22:40:20[Server thread/DEBUG]:  #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /rules)

22:40:20[Server thread/DEBUG]:  #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

22:40:20[Server thread/DEBUG]:  #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

22:40:20[Server thread/DEBUG]:  #8 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

22:40:20[Server thread/DEBUG]:  #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

22:40:20[Server thread/DEBUG]:  #10 src/pocketmine/Player(3056): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

22:40:20[Server thread/DEBUG]:  #11 src/pocketmine/network/mcpe/RakLibInterface(161): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

22:40:20[Server thread/DEBUG]:  #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 104.247.70.76 50717, raklib\protocol\EncapsulatedPacket object, integer 0)

22:40:20[Server thread/DEBUG]:  #13 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()

22:40:20[Server thread/DEBUG]:  #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()

22:40:20[Server thread/DEBUG]:  #15 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)

22:40:20[Server thread/DEBUG]:  #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()

22:40:20[Server thread/DEBUG]:  #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()

22:40:20[Server thread/DEBUG]:  #18 src/pocketmine/Server(2259): pocketmine\snooze\SleeperHandler->sleepUntil(double 1539204020.9791)

22:40:20[Server thread/DEBUG]:  #19 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()

22:40:20[Server thread/DEBUG]:  #20 src/pocketmine/Server(1700): pocketmine\Server->start()

22:40:20[Server thread/DEBUG]:  #21 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/)

22:40:20[Server thread/DEBUG]:  #22 /home/minecraft/pocketmine.phar(1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

Whats going on?

**Comment by xXNiceYT** [comment]
CreateCustomForm not simple

**Comment by Wolfkid200444** [comment]
How do i create CustomForm? @xXNiceYT

**Comment by xXNiceYT** [comment]
$form = $formapi->createCustomForm(function (Player $player, $data){

**Comment by Zadezter** [comment]
Good.

**Comment by Wolfkid200444** [comment]
```

13:06:07[Server thread/CRITICAL]:  Unhandled exception executing command 'rules' in rules: Call to undefined method jojoe77777\FormAPI\CustomForm::setContent()

13:06:07[Server thread/CRITICAL]:  Error: "Call to undefined method jojoe77777\FormAPI\CustomForm::setContent()" (EXCEPTION) in "RulesUI_dev-12.phar/src/WolfGangRule/Rules" at line 54

13:06:07[Server thread/DEBUG]:  #0 RulesUI_dev-12.phar/src/WolfGangRule/Rules(43): WolfGangRule\Rules->mainForm(pocketmine\Player object)

13:06:07[Server thread/DEBUG]:  #1 src/pocketmine/command/PluginCommand(58): WolfGangRule\Rules->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string rules, array Array())

13:06:07[Server thread/DEBUG]:  #2 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string rules, array Array())

13:06:07[Server thread/DEBUG]:  #8 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

13:06:07[Server thread/DEBUG]:  #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

13:06:07[Server thread/DEBUG]:  #21 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/)

13:06:07[Server thread/DEBUG]:  #22 /home/minecraft/pocketmine.phar(1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

13:06:07[Server thread/DEBUG]:  #3 src/pocketmine/Server(1955): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string rules)

13:06:07[Server thread/DEBUG]:  #4 src/pocketmine/Player(2191): pocketmine\Server->dispatchCommand(pocketmine\Player object, string rules)

13:06:07[Server thread/DEBUG]:  #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /rules)

13:06:07[Server thread/DEBUG]:  #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)

13:06:07[Server thread/DEBUG]:  #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)

13:06:07[Server thread/DEBUG]:  #10 src/pocketmine/Player(3056): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

13:06:07[Server thread/DEBUG]:  #11 src/pocketmine/network/mcpe/RakLibInterface(161): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)

13:06:07[Server thread/DEBUG]:  #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 66.87.141.121 30250, raklib\protocol\EncapsulatedPacket object, integer 0)

13:06:07[Server thread/DEBUG]:  #13 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket()

13:06:07[Server thread/DEBUG]:  #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()

13:06:07[Server thread/DEBUG]:  #15 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)

13:06:07[Server thread/DEBUG]:  #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()

13:06:07[Server thread/DEBUG]:  #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()

13:06:07[Server thread/DEBUG]:  #18 src/pocketmine/Server(2259): pocketmine\snooze\SleeperHandler->sleepUntil(double 1539255967.2587)

13:06:07[Server thread/DEBUG]:  #19 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()

13:06:07[Server thread/DEBUG]:  #20 src/pocketmine/Server(1700): pocketmine\Server->start()
```

Now ?

**Comment by xXNiceYT** [comment]
You can’t use setContent

**Comment by Wolfkid200444** [comment]
So what do i use or i remove it?

**Comment by xXNiceYT** [comment]
addLabel

**Comment by Wolfkid200444** [comment]
Oh ok

**Comment by Wolfkid200444** [comment]
Thanks @xXNiceYT

**Comment by Zadezter** [comment]
`addLabel()` for createCustomForm
`setContent()` for createSimpleForm

**Comment by Wolfkid200444** [comment]
```
Now i know
```
